import Head from "next/head"
import UserForm from "../components/Forms/UserForm"

function Form() {
  return (
    <div>
      <Head>
        <title>ProfileSpace | Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserForm />
    </div>
  )
}

export default Form